#! /usr/bin/env python3
from utils import get_clipboard_selected_text, open_firefox_tab

to_look_for = get_clipboard_selected_text()

url = "www.google.com/search?source=hp&q={}".format(to_look_for)

open_firefox_tab(url)