#! /usr/bin/env python3
from utils import get_clipboard_selected_text, open_firefox_tab

to_translate = get_clipboard_selected_text()

url = "www.wordreference.com/enfr/{}".format(to_translate)

open_firefox_tab(url)